# Wayland / Theming – nur für die grafische Session relevant
QT_QPA_PLATFORMTHEME=qt6ct
XCURSOR_THEME=Adwaita
XCURSOR_SIZE=24
MOZ_ENABLE_WAYLAND=1

# Beide Welten – hier für GUI-Apps
EDITOR=nvim --clean
VISUAL=nvim --clean
BROWSER=firefox
NAME=Sven Haardiek
EMAIL=sven@haardiek.de
SSH_AUTH_SOCK=%t/keyring/ssh
